routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','PagesController@getHome');

Route::get('/about','PagesController@getAbout');

Route::get('/contact','PagesController@getContact');

Route::post('/contact/submit','MessagesController@getAbout');

Route::get('/messages','MessagesController@getMessages');


Route::resource('users','UserController');
//Route::resource('company','CompaniesController');
Route::resource('company_categories.companies','CompaniesController');
Route::resource('CompanyCategories','CompanyCategoriesController');

Route::resource('companies.managers','ManagerController');
//Route::resource('companies.coupons','CompanyCouponsController');
//Route::resource('company/{{id}}/coupons/{{couponId}}','CompanyCouponsController');
Route::get('/forms','FormsController@returnForm');

Route::resource('coupons','CouponController');
Route::resource('Coachs','CoachController');
Route::resource('Courses','CourseController');

app/Company.php
<?php

namespace App;


use Illuminate\Database\Eloquent\Model;
use libphonenumber\PhoneNumber;
use libphonenumber\PhoneNumberFormat;
use Plank\Mediable\Mediable;

class Company extends Model
{
    use Mediable;
    protected $hidden = ['approved','created_at','updated_at'];
    protected $with = ['coupons','managers'];
    protected $appends = ['phone2'];


    public function company_subcategory()
    {
        return $this->belongsTo(CompanySubcategory::class);
    }

    public function coupons()
    {
        return $this->hasMany(Coupon::class);
    }

    public function managers()
    {
        return $this->hasMany(Manager::class);
    }


    public function getPhone2Attribute()
    {
        $p = phone($this->phone, ['IL'], PhoneNumberFormat::NATIONAL);
        return $p;
    }

    public function region()
    {
        return $this->belongsTo(Region::class);
    }

    public static function boot()
    {
        parent::boot();

        static::deleting(function (Company $company) {
            $company->coupons()->delete();
            $company->managers()->delete();
        });
    }






}

app/Http/Controllers/CompaniesController.php
<?php

namespace App\Http\Controllers;

use App\Company;
use App\CompanyCategory;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use Illuminate\View\View;
Use Redirect;



class CompaniesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function index(CompanyCategory $companyCategory)
    {
        //echo json_encode($companyCategory);
        $Companies = $companyCategory->companies;
       // echo json_encode($Categories);
        $isEdit = true;
        $Delete = true;
         $Url = "/company";
         $fileds = array('','שם חברה','כתובת','טלפון','פרטים');
         $rows = array('id','title','address','phone2','description');
        //return view('company.index');
       return view('company.index', ['name' => 'id','Title' => 'עסקים' ,'Description' => 'רשימת כל בתי העסק הקיימים'  ,'Companies' => $Companies , 'fileds' => $fileds , 'rows' => $rows , 'isEdit' => $isEdit , 'Delete' => $Delete ,'url' =>$Url]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //echo $id;
       // $Companies = Company::find(1); // Company::find($id);
        //$Companies  = \App\company::where('region_id','=',$id)->orderBy('id','asc')->get();
        //echo $Companies;
        //return view('company.index',['Companies' => $Companies]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(CompanyCategory $companyCategory ,Company $company)
    {
        $company->delete();
        return redirect("company_categories/{$companyCategory->id}/companies");
      //  return view('company.index',['Companies' => $Companies]);
    }
}

resources/views/company/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="formWrapper">
        <div class="row DirectionRtl">
            <div class="col-lg-12">
                <h1 class="page-header">הוספת קופון חדש</h1>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
        <div class="row DirectionRtl" >
            <div class="col-lg-12">
                <div class="panel panel-default" >
                    <div class="panel-heading " >
                        עדכן קופון חדש
                    </div>
                    <div class="panel-body ">
                        <div class="row ">
                            <div class="col-lg-12">
                                <form role="form" action="{!! action('UserController@store') !!}" method="post" >
                                    <div class="row">
                                        <div class="col-lg-6">
                                            <div class="form-group">
                                                <label>מייל הלקוח</label>
                                                <input class="form-control" value="" name="email">
                                            </div>
                                        </div>
                                        <div class="col-lg-6">
                                            <div class="form-group">
                                                <label>שם הלקוח</label>
                                                <input class="form-control" value="" name="name">
                                            </div>
                                        </div>
                                    </div>

                                    <div class="row">
                                        <div class="col-lg-6">
                                            <div class="form-group">
                                                <label>טלפון</label>
                                                <input class="form-control" value="" name="phone">
                                            </div>
                                        </div>
                                        <div class="col-lg-6">
                                            <div class="form-group">
                                                <label>עיר</label>
                                                <input class="form-control" value="" name="city">
                                            </div>
                                        </div>

                                    </div>



                                    <button type="submit" class="btn btn-default DirectionLtr" style="float:left; width: 120px; text-align: center !important;" >שלח קופון</button>
                                    {{csrf_field()}}
                                </form>
                            </div>
                            <!-- /.col-lg-6 (nested) -->
                        </div>
                        <!-- /.row (nested) -->
                    </div>
                    <!-- /.panel-body -->
                </div>
                <!-- /.panel -->
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->

@endsection

resources/views/company/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="formWrapper">
        <div class="row DirectionRtl">
            <div class="col-lg-12">
                <h1 class="page-header">הוספת קופון חדש</h1>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
        <div class="row DirectionRtl" >
            <div class="col-lg-12">
                <div class="panel panel-default" >
                    <div class="panel-heading " >
                        עדכן קופון חדש
                    </div>
                    <div class="panel-body ">
                        <div class="row ">
                            <div class="col-lg-12">
                                <form role="form" action="{!! action('UserController@update', ['id' => $item->id ] ) !!}" method="post" >
                                    <input name="_method" type="hidden" value="PATCH" >
                                    <div class="row">
                                        <div class="col-lg-6">
                                            <div class="form-group">
                                                <label>מייל הלקוח</label>
                                                <input class="form-control" value="{{$item->email}}" name="email">
                                            </div>
                                        </div>
                                        <div class="col-lg-6">
                                            <div class="form-group">
                                                <label>שם הלקוח</label>
                                                <input class="form-control" value="{{$item->name}}" name="name">
                                            </div>
                                        </div>
                                    </div>

                                    <div class="row">
                                        <div class="col-lg-6">
                                            <div class="form-group">
                                                <label>טלפון הלקוח</label>
                                                <input class="form-control" value="{{$item->phone}}" name="phone">
                                            </div>
                                        </div>
                                        <div class="col-lg-6">
                                            <div class="form-group">
                                                <label>עיר</label>
                                                <input class="form-control" value="{{$item->city}}" name="city">
                                            </div>
                                        </div>

                                    </div>



                                    <button type="submit" class="btn btn-default DirectionLtr" style="float:left; width: 120px; text-align: center !important;" >שלח פרטים</button>
                                    {{csrf_field()}}
                                </form>
                            </div>
                            <!-- /.col-lg-6 (nested) -->
                        </div>
                        <!-- /.row (nested) -->
                    </div>
                    <!-- /.panel-body -->
                </div>
                <!-- /.panel -->
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->

@endsection

resources/views/company/index.blade.php
@extends('layouts.app')

@section('content')

    <section id="content">
        <div class="page page-full page-mail">
            <div class="tbox tbox-sm">

                <!-- ====================================================
                ================= Left Bar ===============================
                ===================================================== -->

                <!-- left side -->
                <div class="tcol w-md bg-tr-white lt b-r">

                    <!-- left side body -->
                    <div class="p-15 collapse collapse-xs collapse-sm" id="mail-nav">

                        <ul class="nav nav-pills nav-stacked nav-sm" id="mail-folders">
                            <li class="active"><a href="mail-inbox.html">Inbox <span class="pull-right badge bg-lightred">6</span></a></li>
                            <li><a href="javascript:;">Sent</a></li>
                            <li><a href="javascript:;">Draft</a></li>
                        </ul>

                        <h5 class="b-b p-10 text-strong">Labels</h5>
                        <ul class="nav nav-pills nav-stacked nav-sm" id="mail-labels">
                            <li><a href="javascript:;"><i class="fa fa-fw fa-circle text-primary"></i>Family</a></li>
                            <li><a href="javascript:;"><i class="fa fa-fw fa-circle text-default"></i>Work</a></li>
                        </ul>

                    </div>
                    <!-- /left side body -->
                </div>
                <!-- /left side -->


                <!-- ====================================================
               ================= Content ===============================
               ===================================================== -->

                <!-- right side -->
                <div class="tcol">
                    @if(count($Companies) == 0)
                        <div class="alert alert-warning alert-dismissable" style="direction:rtl; text-align:right;">
                            <strong>לא נמצאו ספקים , <a href="new_supplier.php"> לחצ/י כאן</a> כדי להוסיף ספק.</strong>
                        </div>
                    @endif
                    <div class="p-15 bg-white b-b">

                        <div class="btn-group pull-right">
                            <button type="button" class="btn btn-default">צור קטגורייה חדשה</button>
                        </div>
                        <div class="btn-toolbar">
                        </div>
                    </div>

                    <ul class="list-group no-radius no-border" id="mails-list">
                        @foreach($Companies as $item)

                            <li class="list-group-item b-primary" style="direction:rtl; text-align:right;">
                                <div class="media">
                                    <div class="pull-right">
                                        <div class="thumb thumb-sm" style="width:65px;">
                                            <a href=""><img class="img-circle" style="height:65px !important; width:65px !important" border="0" src="https://wordsmith.org/words/images/avatar2_large.png"></a>
                                        </div>
                                    </div>
                                    <div class="media-body">
                                        <div class="media-heading m-0">
                                            <a href="" class="mr-1">{{$item->title}}</a>
                                            <span class="pull-left text-sm text-muted" >
                                                <div class="hidden-xs" style="margin-top:5px;">
                                                    <a href="/coupons/{{$item->id}}" >
                                                        <button  class="btn btn-primary btn-ef btn-ef-7 btn-ef-7b mb-10" style="font-weight:bold; direction:rtl; background-color:#0C3;">
                                                            <span class="badge bg-lightred" style="margin-right:4px;">{{ count($item->coupons) }} </span> מספר קופונים<i class="glyphicon glyphicon-gift" style="padding-top:5px; "></i>
                                                        </button>
                                                    </a>
                                                    <a href="">
                                                        <button  class="btn btn-primary btn-ef btn-ef-7 btn-ef-7b mb-10" style="font-weight:bold; direction:rtl; background-color:#666">ערוך קטגורייה
                                                            <i class="glyphicon glyphicon-edit" style="padding-top:5px;  "></i>
                                                        </button>
                                                    </a>
                                                    {{--<form action=" {{route('company_categories.companies.destroy' , $item->id)}}" method="post">--}}
                                                    <form action="{!! action('CompaniesController@destroy' , ['company_category'=>1, 'company'=> $item->id]) !!}" method="post">
                                                        <input type="hidden" name="_method" value="DELETE">
                                                        <button onClick=""  type="submit" class="btn btn-primary btn-ef btn-ef-7 btn-ef-7b mb-10" style="font-weight:bold; direction:rtl">מחיקת חברה
                                                            <i class="glyphicon glyphicon-trash" style="padding-top:5px; "></i>
                                                        </button>
                                                        {{csrf_field()}}
                                                    </form>

                                                </div>
                                            </span>
                                        </div>
                                        <div>{{$item->title}}</div>
                                    </div>
                                </div>
                            </li>

                        @endforeach
                    </ul>
                    <!-- / mails -->
                    <!-- /right side body -->
                </div>
                <!-- /right side -->
            </div>
        </div>
    </section>
    <!--/ CONTENT -->
@endsection

resources/views/company/index1.blade.php
@extends('layouts.app')

@section('content')
    <div class="MyTable">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">{{$Title}}</h1>
            </div>
            <!-- /.col-lg-12 -->
        </div>

        <!-- /.row -->
        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        {{$Description}}

                        <a href="{{$url}}/create"><button type="submit" class="btn btn-default DirectionLtr" style="float:left; width: 120px; text-align: center !important; margin-top: -3px; padding: 2px !important;" >צור עסק חדש</button></a>

                    </div>

                    <!-- /.panel-heading -->
                    <div class="panel-body">
                        <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
                            <thead >
                            <tr class="DirectionRtl">
                                @foreach($fileds as $filed)
                                    <th>&nbsp; {{$filed}}</th>
                                @endforeach
                                <th class="W80">&nbsp; עובדים </th>
                                <th class="W80">&nbsp; קופונים </th>
                                @if($isEdit)
                                    <th class="W40">&nbsp; ערוך</th>
                                @endif
                                @if($Delete)
                                    <th class="W40">&nbsp;מחק</th>
                                @endif
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($Categories as $item)
                                <tr class="odd gradeX">
                                    @foreach($rows as $row)
                                        <td>{{$item->$row}}</td>
                                    @endforeach

                                    <th  style="text-align: center"><a href="companies/{{$item->id}}/managers"><button class="btn btn-default W40" type="submit" > {{ count($item->managers) }} </button></a> </th>
                                    <th  style="text-align: center"><a href="coupons/{{$item->id}}"><button class="btn btn-default W40" type="submit" > {{ count($item->coupons) }} </button></a></th>
                                    @if($isEdit)
                                        <td style="text-align: center"><a href="{{$url}}/{{$item->id}}/edit" class="btn btn-default" role="button"><i class="fa fa-pencil-square-o"></i></a> </td>
                                    @endif
                                    @if($Delete)
                                        <form action="{{ action('UserController@destroy', ['id' => $item->id] ) }}" method="post">
                                            <input type="hidden" name="_method" value="DELETE">
                                            <th  style="text-align: center"><button class="btn btn-default" type="submit" > <i class="fa fa-trash-o"></i></button></th>
                                            {{csrf_field()}}
                                        </form>
                                    @endif
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                    <!-- /.panel-body -->
                </div>
                <!-- /.panel -->
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->

    </div>
@endsection